name: End-to-End Tests
on: [push]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Run Meteor commands
        shell: bash -l {0}
        run: |
          meteor npm install
          meteor npm run lint
          meteor npm run testcafe-ci
      - name: Run tests
        shell: bash -l {0}
        run: |
          meteor npm run testcafe

